Emissary Ingress replaces Ambassador
doc-ai/terraform-modules pull request #54
Opened 2022-12-22 02:25 UTC by benlivengood

2022-12-22 17:13 UTC, bluehawk27 requested changes

2022-12-22 17:13 UTC, bluehawk27 commented on cloud-native/ambassador/templates/values.yaml
> +        app: toniq-api-v1
PR looks good, we probably need to change this to match whatever emissary launches with now.

2022-12-22 17:21 UTC, bluehawk27 submitted a review, later dismissed

2022-12-22 18:34 UTC, benlivengood commented on cloud-native/ambassador/templates/values.yaml
> +        app: toniq-api-v1
Done

2022-12-22 18:52 UTC, bluehawk27 submitted a review, later dismissed

2023-01-04 22:21 UTC, bluehawk27 approved these changes

2023-01-04 23:38 UTC, merged